---
title: "Possible Ke and Xi values"
date: "2014-11-01"
output:
  html_document:
    toc: true
---

Codes
================================================================================

```{r, echo=FALSE, eval=FALSE}
.outdir = '~/edal/html/results'
rmarkdown::render('~/edal/ke_xi.Rmd', output_dir=.outdir)
```

```{r library}
library(plyr)
library(dplyr)
library(stringr)
library(tidyr)
library(pipeR)
library(ggplot2)
library(gridExtra)
```

```{r functions}
theme_tile =
    theme(panel.background=element_rect(fill='white', colour='black'))+
    theme(panel.grid=element_blank())+
    theme(axis.ticks=element_blank())+
    theme(axis.text=element_blank())
heat_colours = c('#000000', '#0000FF', '#00FFFF', '#00FF00', '#FFFF00', '#FF0000')
scale_fill_heat = scale_fill_gradientn(colours=heat_colours)
is.odd = function(x) x %% 2 != 0

.plot_ke = function(.indir) {
    .raw = read.csv(file.path(.indir, 'possible_ke_xi.csv.gz'))
    .tidy = .raw %>>%
        gather(key, Ke, starts_with('Ke'))
    .p = .tidy %>>%
        filter(is.odd(height), is.odd(diameter)) %>>%
        filter(key=='Ke_v3an' | key=='Ke_v3u') %>>%
        mutate_each(funs(f = . / 16), height, diameter, height_pref, diameter_pref) %>>%
        ggplot(aes(x=height_pref, y=diameter_pref))
    .p = .p + geom_tile(aes(fill=Ke))
    .p = .p + facet_grid(diameter ~ key + height, as.table=FALSE, labeller=label_both)
    .p = .p + labs(title=basename(.indir))
    .p = .p + theme_tile + scale_fill_heat
    .p = .p + theme(strip.text=element_text(size=rel(0.6)))
    .p
}

.plot_psi = function(.indir) {
    .raw = read.csv(file.path(.indir, 'possible_ke_xi.csv.gz'))
    .tidy = .raw %>>%
        gather(key, Xi, starts_with('Xi'))
    .p = .tidy %>>%
        filter(is.odd(height), is.odd(diameter)) %>>%
        filter(key!='Ke_v3') %>>%
        mutate_each(funs(f = . / 16), height, diameter, height_pref, diameter_pref) %>>%
        ggplot(aes(x=height_pref, y=diameter_pref))
    .p = .p + geom_tile(aes(fill=Xi))
    .p = .p + facet_grid(diameter ~ key + height, as.table=FALSE, labeller=label_both)
    .p = .p + labs(title=basename(.indir))
    .p = .p + theme_tile + scale_fill_heat
    .p = .p + theme(strip.text=element_text(size=rel(0.6)))
    .p
}
```

Results
================================================================================

```{r plot, echo=FALSE, fig.width=14, fig.height=8}
.indir = 'default_20141103_020244_75110@pohjola-2.local'
.indir = file.path('~/tmp/out20141103', .indir)
.plot_ke(.indir)
.plot_psi(.indir)
```
